Forget Password #4
ousl-groupE5-ExpiryInspector/ExpiryInspector pull request #53
Opened 2024-09-16 16:55 UTC by Sahani13

Implemented forget password code.

2024-09-16 22:11 UTC, Pradeepkumara95 requested changes
Add the popup alert to the button component. follow comments

2024-09-16 22:11 UTC, Pradeepkumara95 commented on Frontend/src/screens/FogotPassword.js
> +      <ImageComponentAuth source={require('../../assets/Reset_Pasword.png')}/>
Image is missing, please commit the right image with the same name written here.

2024-09-16 22:11 UTC, Pradeepkumara95 commented on Frontend/src/screens/FogotPassword.js
> +    navigation.navigate('Dashboard');
redirect to the login page

2024-09-16 22:11 UTC, Pradeepkumara95 commented on Frontend/src/screens/FogotPassword.js
> +import { Text, TouchableOpacity, View, StyleSheet } from 'react-native';
import {Alert}

2024-09-16 22:11 UTC, Pradeepkumara95 commented on Frontend/src/screens/FogotPassword.js
> +  const handleFogetPasword = () => {
Alert.alert(
      "Title",
      "Please check your e mail",)

2024-09-17 14:10 UTC, sarasikarunanayaka approved these changes
Forget password page UI implementation is running without any errors.

2024-09-18 08:18 UTC, Pradeepkumara95 approved these changes
UI is completed

2024-09-18 08:19 UTC, merged